### ISSUE TITLE
Cannot export Mapper

### ISSUE THREAD

**Issue by irinaz** [SU-SWS/stanford_capx#121]
Hi, 
when I want to export mapper I get the following error, not sure how to deal with it.  I do not see any additional information in the log.  sheamck@stanford.edu has admin permissions on this site.

From http://cap-kipac7-clean.pantheonsite.io/admin/config/capx/preset/export/mapper/kipac_mapper?destination=admin/config/capx/mapper

    Notice: Undefined index: ctools_export_form in drupal_retrieve_form() (line 807 of /srv/bindings/80d1ea1e8fb74e2db7b8411c10ee026d/code/includes/form.inc).
    Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'ctools_export_form' not found or invalid function name in drupal_retrieve_form()(line 842 of /srv/bindings/80d1ea1e8fb74e2db7b8411c10ee026d/code/includes/form.inc).

**Comment by sherakama** [comment]
Seems to be working for me.

![screen shot 2017-03-16 at 12 23 45 pm](https://cloud.githubusercontent.com/assets/550602/24014791/71895e8e-0a43-11e7-9a26-f4947b9432d7.png)

Please try again. 

The error suggests that ctools is missing or is loaded at the wrong time. Please validate your version of ctools and the weight in which it is bootstrapped.

**Comment by irinaz** [comment]
This is very interesting. I tested again and getting the same problem. 
We are working on the same site, so I would guess that loading should 
work in the same way. I have older version of Chrome, I will test with 
safari or firefox and let you know.

Thanks a lot for taking care of this right away!

**Comment by irinaz** [comment]
I have tested in both Safari and Firefox and get the same error.  Clearly if it works for you the problem is on my laptop. I will need to find another hardware to test and will report back. 
thanks!

**Comment by irinaz** [comment]
I tested it today again, and export works fine.  Not sure what was going wrong with ctools.
Thanks, Irina

**Comment by sherakama** [comment]
Glad to hear the issue has been resolved.
