### ISSUE TITLE
Seeing "Field field_s_person_type was removed from the system" error after upgrading module

### ISSUE THREAD

**Issue by dgiul** [SU-SWS/stanford_capx#137]
Until several weeks ago the Stanford EH&S website was running version 7.x-1.3 of the CAPx module. After upgrading to 7.x-2.1 we started seeing a message at the top of every page while logged into the admin account that says:

```
Field field_s_person_type was removed from the system, but is still used in CAP Profiles to Stanford Person. You should check configuration of the specified mappers!
```

The module seems to be working okay, I'm just not sure what the best way to clear that message is. Any suggestions?

**Comment by sherakama** [comment]
Hey Dan,

That error message refers to a mapper that is trying to map to a field that no longer exists. I would recommend reviewing and re-saving your configured mappers. That should clear up the error for you.

**Comment by sherakama** [comment]
Also, 
I would recommend upgrading to the 7.x-3.0-beta7 release as it has a number of improvements and bug fixes that 2.1 does not.

**Comment by dgiul** [comment]
Cool, that fixed it. Thanks!!

Thanks for the tip about 7.x-3.0-beta7 too, I'll push that update out to our site this week.

**Comment by sherakama** [comment]
Glad to hear it.
