### ISSUE TITLE
Max number of SUNets on non-dept, non-WG queries

### ISSUE THREAD

**Issue by zchandler** [SU-SWS/stanford_capx#153]
Hi Team! @sherakama , As usual I am doing something weird with this module. I have to import a large number of profiles that do not correspond to any dept or workgroup. I have a list of 1041 sunets, comma separated.  My import works fine when I chunk it up into digestible bits, but gags if I try the whole thing. Might I ask what the max number if individual sunets is? Is there a hard ceiling? I could get their by trial and error, but I figured that would probably be mostly error. :)
Cheers,
Zach

**Comment by zchandler** [comment]
Or might it be that I am passing a string that is not a valid SUNet? That might be the case ... I hit Save on the importer, and it doesn't bring in any new data.

**Comment by sherakama** [comment]
Hey Zach,

CAPx provides pretty verbose logging. Can you check watchdog and see if there are any critical errors in there?

**Comment by zchandler** [comment]
Will do Shea, thanks.  I ended up making 2 importer groups, one with slightly less than 500, and one with slightly more. The bigger one isn't connecting, I get 6 fail messages every time I try to import, 1 error per batch. I will do some digging to find out why it's not happy.

**Comment by sherakama** [comment]
Often these types of things end up being PHP memory issues where some check or loop is trying to put too many values in to a single object in memory. If you can have a look for PHP errors.

**Comment by zchandler** [comment]
in dblog?

**Comment by zchandler** [comment]
BTW, in the last 2 CAPx related projects I have made use of Relationship with CAPx importer in Views, thanks so much for building that in!

**Comment by zchandler** [comment]
Whoa, not WSOD but almost:
<img width="1093" alt="screen shot 2017-11-14 at 5 05 31 pm" src="https://user-images.githubusercontent.com/574978/32813276-231c42f4-c95e-11e7-9119-b44e46c1d148.png">

Don't waste too much time on this man, I will figure it out eventually. :)

**Comment by zchandler** [comment]
Houston, I might have a problem here.
Looks like I might be on an older version of CAPx for this website. From dblog:

`Notice: Trying to get property of non-object in CAPx\Drupal\Util\CAPxImporter::loadEntityImporter() (line 79 of /afs/.ir.stanford.edu/dist/drupal/ds_zcprototyping/modules/stanford_capx-7.x-1.x/includes/CAPx/Drupal/Util/CAPxImporter.php).`

Can you check on this, svp?

**Comment by zchandler** [comment]
Also got this weird notice:

`Impossible to load mapping confiruration with key.`

**Comment by zchandler** [comment]
OK, so I moved over to the /mimisbrunnr/ site bcs it has capx 3.x installed. Still having same problem. Current theory: this is a problem with the input I am feeding the machine. One set of sunets (486) works as expected. Another importer with fewer (~200) chokes, and the error msg says Internal Server Error, but I don't see how it can be anything besides a problem with the data I am feeding in.  Maybe one of the sunets is not a valid sunet?

**Comment by sherakama** [comment]
Looks like you are getting an out of memory issue. I ran the `FDP dwan-jrao` importer and got:

[Thu Nov 16 09:07:24.161703 2017] [:error] [pid 22832] [client 171.66.23.46:56915] FastCGI: server "/var/www/ds_zcprototyping/public_html/php.fcgi" stderr: PHP Fatal error:  Allowed memory size of 157286400 bytes exhausted (tried to allocate 77 bytes) 

This is likely caused by one or more of the profiles being "large". Those with many publications tend to be the culprits. Tracking down this person is tricky as the error logs won't tell you who in the huge response has lots of data on their profile. Swagger console can help you in this case.

**Comment by zchandler** [comment]
Thanks Shea! I got through it!  I was only bringing in very small text fields, but maybe the client has to load the whole object before extracting what it needs? Anyhow, I got through by breaking it up into importers of less than 100.  The first round was 500+ so I couldn't figure out why ... your Large Object Theory is the best explanation. Anyways, all done! Thanks for checking back in.

**Comment by sherakama** [comment]
Yes, unfortunately we are at the mercy of the API. The API has only a few response formats for a profile and the one we have to use is EVERYTHING. Even if you are just wanting to pull the name we have to pull the whole profile. This gets loaded in to PHP memory and quickly eats up resources. Not much we can do about it on our end.

**Comment by zchandler** [comment]
Now I get it. Thanks. Maybe I will try to add a developer story to the CAP backlog for this this year. Do you think that this could be solved with query parameters?
i.e. ?pubs=false
Z.

________________________________________

**Comment by sherakama** [comment]
I have a long term vision of being able to pass through the fields/schema of information that I want to the request and get back only that data. That is my ideal state but with D8 out there and a chance at redesigning the way the interface works maybe we can settle on a few different response schemas and limit the complexity of the ui.
