### ISSUE TITLE
Mapping WSOD

### ISSUE THREAD

**Issue by labbydev** [SU-SWS/stanford_capx#58]
Attempting to set up capx with the profiles module when I go I navigate to `/admin/config/capx/mapper/new` I get a WSOD. If I `drush cc all` and refresh the page I get the following error:

```
PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'default.block' doesn't exist: SELECT * FROM {block} WHERE module = :module AND delta = :delta; Array ( [:module] => stanford_capx [:delta] => data_browser_launch ) in block_load() (line 709 of /var/www/sites/ehs.local/www/modules/block/block.module).
```

**Comment by sherakama** [comment]
hmm, this looks like we may have to declare `block` as a dependency. 

Thanks for this.

**Comment by labbydev** [comment]
I would agree that would be nice.
