### ISSUE TITLE
Images imported via CAPx disappearing from site

### ISSUE THREAD

**Issue by wkcwells** [SU-SWS/stanford_capx#60]
Images for faculty, postdocs, etc. imported from CAP profiles disappear from our site seemingly at random.  This seems to happen every couple of days.  Over the past few weeks, a few images would disappear here and there, but over last weekend, all but 2 of the faculty images disappeared.

The images can be recovered by updating the individual people imports (on the person edit page), but not by updating all of the profiles in the CAPx admin interface.  That brought back two of the images.

This is in reference to the SITP website currently under development.  This is a showstopper for the launch of our site which is targeted for 1/14.

**Comment by sherakama** [comment]
Hello @wkcwells,

Thank you for this bug report. We have been tracking this error for a couple of weeks now. Marion has been able to provide us with great information and has helped notify us when this issue occurs. We have confirmed it is not a data integrity issue from the API and have eliminated that as a possibility. We have narrowed down the issue to something that happens specifically on the Stanford Web Services hosting environment roughly every two days. This issue has not been able to be reproduced in other environments. I have spoken to the other developers on our team and we have discussed a possible solution that can be implemented at the CAPx module level. We should be able to have this issue fixed shortly and your launch timeline should not be impacted. 

Thanks again,
