### ISSUE TITLE
Orphan isn't detected

### ISSUE THREAD

**Issue by labbydev** [SU-SWS/stanford_capx#74]
I'm using the CAPx profile to sync CAP profiles to the stanford_person for the EH&S website. I have it set to unpublish orphaned profiles. However, when I run it doesn't seem to detect the orphan. I've run it a couple of times and it will not automatically unpublish the profile it still indicates that the profile is not orphaned, but when I click "View on CAP" it goes to a 404 (https://profiles.stanford.edu/42311). Any idea why this would be happening?

**Comment by sherakama** [comment]
Which version are you running?

There were some recent fixes on the orphan handling that made it in to the 1.3 release.
eg: https://github.com/SU-SWS/stanford_capx/commit/11873571e78e89bb348bd36fd6cdc8b31479a687

**Comment by labbydev** [comment]
I'm using 1.2, do you think upgrading would resolve the issue?

**Comment by sherakama** [comment]
I am not sure but it can't hurt to try. 

What is the url of the website you are developing on?

**Comment by sherakama** [comment]
2 years of inactivity. Closing.
