### ISSUE TITLE
Old version of PHP (5.4) causes CAPx configuration to fail silently

### ISSUE THREAD

**Issue by wkcwells** [SU-SWS/stanford_capx#75]
I have a test Drupal instance on AWS and I loaded the CAPx module from this repo.  Basic CAPx configuration (trying to set credentials) would spin forever in the UI.  Finally traced the problem to the default PHP version for the AMI I was using being too old (5.4).

**Comment by sherakama** [comment]
Thanks for the issue Kevin.

We have a PHP 5.4 compatible branch at: https://github.com/SU-SWS/stanford_capx/tree/php54

We are not planning to support this long term as PHP 5.4 is already past it's end of life and is no longer maintained by the PHP community. I would highly recommend upgrading your PHP version as 5.4 could have security holes in it. 

Also, I have found that the CAPx module crashes hard when not using PHP 5.5 or greater and spits out all sorts of errors. Do you have display_errors on and the error level set?

http://php.net/manual/en/errorfunc.configuration.php#ini.error-reporting

**Comment by wkcwells** [comment]
I upgraded previously and everything works fine now.  I will check my error reporting settings.  

So this issue is really about the "spin forever" with the wrong version of PHP.

Also perhaps documentation the environment requirements.  Would you like to me to file a separate issue for that?  I can also make a simple change to the README and file a PR as well if that's appropriate.

**Comment by sherakama** [comment]
I think a system requirements section in the readme is a great idea. No need for a new issue as we can use this one. I'd be happy to accept a PR with this documentation. File away!

Thanks

**Comment by wkcwells** [comment]
Shea, I created pull request #83 for this.  (I am not seeing it linked here, so I must have done something wrong.)  It's almost laughably trivial, as I don't really know the system requirements.  But it's a start.  Thanks!
