### ISSUE TITLE
Critical security issue

### ISSUE THREAD

**Issue by labbydev** [SU-SWS/stanford_capx#76]
This module is affected by httpoxy and it's a critical security issue for websites using it. Basically, this boils down to a poor assumption in guzzle/guzzle where it trusts the HTTP_PROXY environment variable

https://httpoxy.org/
https://www.drupal.org/SA-CORE-2016-003

**Comment by sherakama** [comment]
Thanks for the heads up on this. We have received the security advisory and are taking the appropriate steps on our hosting environments. Their doesn't appear to be a fix for this issue in 'user land' so we are going to have to roll out updates to apache. I will use this ticket as a reminder to place documentation about this vulnerability in the README.md and possibly write a test in the module.

Thanks again for the post. Much appreciated.

**Comment by zchandler** [comment]
I think it's okay to close this. We added httpoxy documentation to help developers mitigate risk at the server level.

**Comment by sherakama** [comment]
Thanks!
