### ISSUE TITLE
Trouble mapping fields to User Entities

### ISSUE THREAD

**Issue by zchandler** [SU-SWS/stanford_capx#79]
Hi @sherakama !  So I got a little ambitious and decided to map fields from the CAP API to custom User entity fields on a Sites site: newfaculty.stanford.edu.  My first time mapping to non-nodes. (hold onto your butts!)

Here's a couple stumbling blocks I hit:
Since username and email are naturally required by Drupal, it wouldn't let me get away with not specifying which CAP fields I wanted to pull those from:

<img width="815" alt="screen shot 2016-08-16 at 1 55 03 pm" src="https://cloud.githubusercontent.com/assets/574978/17715975/9b62f596-63bb-11e6-90d1-3e227675c9b3.png">

I guessed that I should use $uid for username, but I think that this might be problematic for WebAuth module. When the users were created they did not have realnames display on the user entities, nor did it integrate with WMD Role Mappings, the new users had no roles.

<img width="1190" alt="screen shot 2016-08-16 at 2 02 21 pm" src="https://cloud.githubusercontent.com/assets/574978/17716045/e18b8402-63bb-11e6-8479-cbcbe044c39e.png">

I think I am going to back out of this implementation strategy for now, and import to Person nodes instead. But I think that we should tackle this when we have time.

Thanks!
~Zach

**Comment by zchandler** [comment]
Because I am going to Plan B this approach, there is no urgency to this ticket, at least not on my account.

**Comment by sherakama** [comment]
Hey Zach,

CAPx and Webauth currently do not talk to each other. I suspect this would be a natural fit as all the right pieces are there. It would make sense to have a supporting module that enabled the correct webauth mappings on user creation.

The new SimpleSAML module will be able to provide this functionality in the future as it 'matching' functionality where it will pick up existing user accounts and make them able to be authenticated.

You can see this large body of work here: https://github.com/SU-SWS/stanford_ssp/pull/5
The ssp module is not ready for production yet.

**Comment by sherakama** [comment]
I have added this feature request to our suggestion box. It will get sized and prioritized next week.

Thanks!

**Comment by sherakama** [comment]
https://jumpstart.stanford.edu/suggestion-box/whats-in-the-box

**Comment by sherakama** [comment]
This functionality now exists in the 7.x-3.x branch: https://github.com/SU-SWS/stanford_capx/tree/7.x-3.x/modules/capx_webauth
